

export const identityTags = [
    { label: "Native/indigenous", isChecked: false },
    { label: "Asian", isChecked: false },
    { label: "Hispanic/Latino", isChecked: false },
    { label: "Black", isChecked: false },
    { label: "BAME", isChecked: false },
    { label: "(Dis)Abled", isChecked: false },
    { label: "Estranged", isChecked: false },
    { label: "Working Class", isChecked: false },
    { label: "State School", isChecked: false },
    { label: "Career Leaver", isChecked: false },
    { label: "Low-income", isChecked: false },
    { label: "First-Generation", isChecked: false },
    { label: "Immigrant", isChecked: false },
    { label: "Non-binary", isChecked: false },
    { label: "LGBTQ+", isChecked: false },
    { label: "Man", isChecked: false },
    { label: "Woman", isChecked: false },
    { label: "Sikh", isChecked: false },
    { label: "Buddhist", isChecked: false },
    { label: "Atheist/Agnostic", isChecked: false },
    { label: "Hindu", isChecked: false },
    { label: "Muslim", isChecked: false },
    { label: "Christian", isChecked: false },
    { label: "Jewish", isChecked: false },
]

export const interestTags = [
    { label: "Computer Science", isChecked: false },
    { label: "Engineering", isChecked: false },
    { label: "Architecture", isChecked: false },
    { label: "Business", isChecked: false },
    { label: "Medicine", isChecked: false },
    { label: "Law & Government", isChecked: false },
    { label: "Finance", isChecked: false },
    { label: "Consulting", isChecked: false },
    { label: "Non-profits/NGOs", isChecked: false },
    { label: "Healthcare", isChecked: false },
    { label: "Technology", isChecked: false },
    { label: "Education", isChecked: false },
    { label: "Entrepreneurship", isChecked: false },
    { label: "Politics", isChecked: false },
    { label: "Psychology", isChecked: false },
    { label: "Design", isChecked: false },
    { label: "Sustainability", isChecked: false },
    { label: "Science", isChecked: false },
    { label: "Art", isChecked: false },
    { label: "Religion", isChecked: false },
    { label: "Real Estate", isChecked: false },
    { label: "Hospitality", isChecked: false },
    { label: "Culinary", isChecked: false },
    { label: "Journalism", isChecked: false },
]

export const passionTags = [
    { label: "Writing", isChecked: false },
    { label: "Music", isChecked: false },
    { label: "Art & Theatre", isChecked: false },
    { label: "Games", isChecked: false },
    { label: "Travel", isChecked: false },
    { label: "Reading", isChecked: false },
    { label: "Chess", isChecked: false },
    { label: "Cooking", isChecked: false },
    { label: "Dance", isChecked: false },
    { label: "Photography", isChecked: false },
    { label: "Fashion", isChecked: false },
    { label: "Foreign Languages", isChecked: false },
    { label: "Gardening", isChecked: false },
    { label: "Meditation & Yoga", isChecked: false },
    { label: "History", isChecked: false },
    { label: "Podcasts", isChecked: false },
    { label: "Film & Entertainment", isChecked: false },
    { label: "Singing", isChecked: false },
    { label: "Pets & Animals", isChecked: false },
    { label: "Comedy", isChecked: false },
    { label: "Volunteering", isChecked: false },
    { label: "Shopping", isChecked: false },
    { label: "Sports", isChecked: false },
]